#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HANGMAN.Resource", IsApplication=true)]

namespace HANGMAN
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int freeman = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hangman10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hangman11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hangman12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hangman6 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hangman7 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hangman8 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hangman9 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int HMSetUp3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int LostImage = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tigersplash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int WinImage = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060037
			public const int LL1 = 2131099703;
			
			// aapt resource value: 0x7f06003b
			public const int LL2 = 2131099707;
			
			// aapt resource value: 0x7f060041
			public const int LL3 = 2131099713;
			
			// aapt resource value: 0x7f060044
			public const int LL4 = 2131099716;
			
			// aapt resource value: 0x7f060036
			public const int LLMain = 2131099702;
			
			// aapt resource value: 0x7f06000d
			public const int btnA = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnB = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int btnC = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int btnD = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int btnE = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int btnF = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int btnG = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int btnH = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int btnI = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int btnJ = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int btnK = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int btnL = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int btnM = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int btnN = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int btnO = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int btnP = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int btnQ = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int btnR = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int btnS = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int btnT = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int btnU = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int btnV = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int btnW = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int btnX = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int btnY = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int btnZ = 2131099686;
			
			// aapt resource value: 0x7f06003a
			public const int ivResult = 2131099706;
			
			// aapt resource value: 0x7f060005
			public const int ivStatus = 2131099653;
			
			// aapt resource value: 0x7f06002a
			public const int lvHScore = 2131099690;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06002d
			public const int textView1 = 2131099693;
			
			// aapt resource value: 0x7f06003d
			public const int tvCorrectWord = 2131099709;
			
			// aapt resource value: 0x7f060032
			public const int tvDummy = 2131099698;
			
			// aapt resource value: 0x7f06003e
			public const int tvEnterNameTxt = 2131099710;
			
			// aapt resource value: 0x7f06002b
			public const int tvHSMenu = 2131099691;
			
			// aapt resource value: 0x7f060034
			public const int tvHScore = 2131099700;
			
			// aapt resource value: 0x7f060030
			public const int tvInfo = 2131099696;
			
			// aapt resource value: 0x7f06002e
			public const int tvInfoMenu = 2131099694;
			
			// aapt resource value: 0x7f060009
			public const int tvLength = 2131099657;
			
			// aapt resource value: 0x7f060042
			public const int tvMenu = 2131099714;
			
			// aapt resource value: 0x7f060031
			public const int tvOff = 2131099697;
			
			// aapt resource value: 0x7f06003f
			public const int tvPName = 2131099711;
			
			// aapt resource value: 0x7f060027
			public const int tvPatentG = 2131099687;
			
			// aapt resource value: 0x7f06002c
			public const int tvPatentHS = 2131099692;
			
			// aapt resource value: 0x7f06002f
			public const int tvPatentI = 2131099695;
			
			// aapt resource value: 0x7f060035
			public const int tvPatentM = 2131099701;
			
			// aapt resource value: 0x7f060045
			public const int tvPatentS = 2131099717;
			
			// aapt resource value: 0x7f060033
			public const int tvPlay = 2131099699;
			
			// aapt resource value: 0x7f060043
			public const int tvPlayAgain = 2131099715;
			
			// aapt resource value: 0x7f060039
			public const int tvResult = 2131099705;
			
			// aapt resource value: 0x7f060004
			public const int tvScore = 2131099652;
			
			// aapt resource value: 0x7f060040
			public const int tvSubmit = 2131099712;
			
			// aapt resource value: 0x7f06003c
			public const int tvTextCorrectWord = 2131099708;
			
			// aapt resource value: 0x7f060008
			public const int tvTextLength = 2131099656;
			
			// aapt resource value: 0x7f060038
			public const int tvTextResult = 2131099704;
			
			// aapt resource value: 0x7f060003
			public const int tvTextScore = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int tvTextTries = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int tvTextUsed = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int tvTries = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int tvUsed = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int tvWordToGuess = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int txtviewPlayer = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int txtviewScore = 2131099650;
			
			// aapt resource value: 0x7f060028
			public const int txtvwPlayer = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int txtvwScore = 2131099689;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomRowHS = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HighScore = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Info = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Score = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int longtext = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
